# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupIn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GroupIn
  pod 'Firebase/Core'

  target 'GroupIn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupInTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GroupIn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GroupIn-tvOS

  target 'GroupIn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
