version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17.4
    environment:
      NODE_ENV: test
    steps:
      - checkout

      - restore_cache:
          key: npm-dependencies

      - run:
          name: Create mobile link
          command: |
            cd mobile
            ./create_links.sh
            yarn

      - run:
          name: Installing client packages
          command: |
            cd mobile
            yarn

      - run:
          name: Installing server packages
          command: |
            cd server
            yarn

      - save_cache:
          paths:
            - server/node_modules
            - mobile/node_modules
          key: npm-dependencies
            
      - run:
          name: ESLint Mobile
          command: |
            cd mobile
            yarn run compile
            yarn run lint
                        
      - run:
          name: ESLint Server
          command: |
            cd server
            yarn run compile
            yarn run lint

      - store_artifacts:
          path: server/log

      - store_artifacts:
          path: .coverage
