version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
      - image: mongo:3.6
    environment:
      NODE_ENV: test
    steps:
      - checkout

      - restore_cache:
          key: npm-dependencies

      - run:
          name: Installing server packages
          command: |
            cd server
            yarn

      - run:
          name: Installing client packages
          command: |
            cd mobile
            yarn

      - save_cache:
          paths:
            - server/node_modules
            - mobile/node_modules
          key: npm-dependencies
            
      - run:
          name: Running Tests
          command: |
            cp ./mobile/config/env.js.example ./mobile/env.js
            cp ./mobile/config/firebase_android_config.json.example ./server/firebase_android_config.json
            cd server
            npm test

      - store_artifacts:
                path: ~/.npm/_logs
                destination: logs
