# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - groupin

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Create mobile link
      run: |
        cd server/src/mobile
        ./create_links.sh

    - name: Installing client packages
      run: |
        cd mobile
        yarn

    - name: Installing server packages
      run: |
        cd server
        yarn

    - name: ESLint Mobile
      run: |
        cd mobile
        yarn run compile
        yarn run lint

    - name: ESLint Server
      run: |
        cd server
        yarn run compile
        yarn run lint

    - name: Tests
      run: |
        cd server
        yarn test

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'groupin'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d4339fc6c6944459b37776adf2cc343 }}
        package: .